// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx2B2RGdyVJExrC5NhSJgH-BVVjxkxPgo',
    appId: '1:504575499202:web:a6506a0fc00656c1a2d45b',
    messagingSenderId: '504575499202',
    projectId: 'open-b943d',
    authDomain: 'open-b943d.firebaseapp.com',
    databaseURL: 'https://open-b943d.firebaseio.com',
    storageBucket: 'open-b943d.firebasestorage.app',
    measurementId: 'G-1CTGC0RDC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB-vtOQD5qOCWsbE_Qme0LFpR2bpI70To',
    appId: '1:504575499202:android:d5cf7455856c0835a2d45b',
    messagingSenderId: '504575499202',
    projectId: 'open-b943d',
    databaseURL: 'https://open-b943d.firebaseio.com',
    storageBucket: 'open-b943d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsSczlptsFMvErjAEiE9JD_i_0RzYmv-A',
    appId: '1:504575499202:ios:122c56b483797d2ea2d45b',
    messagingSenderId: '504575499202',
    projectId: 'open-b943d',
    databaseURL: 'https://open-b943d.firebaseio.com',
    storageBucket: 'open-b943d.firebasestorage.app',
    iosBundleId: 'com.example.calmy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsSczlptsFMvErjAEiE9JD_i_0RzYmv-A',
    appId: '1:504575499202:ios:122c56b483797d2ea2d45b',
    messagingSenderId: '504575499202',
    projectId: 'open-b943d',
    databaseURL: 'https://open-b943d.firebaseio.com',
    storageBucket: 'open-b943d.firebasestorage.app',
    iosBundleId: 'com.example.calmy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx2B2RGdyVJExrC5NhSJgH-BVVjxkxPgo',
    appId: '1:504575499202:web:2212563b4905798da2d45b',
    messagingSenderId: '504575499202',
    projectId: 'open-b943d',
    authDomain: 'open-b943d.firebaseapp.com',
    databaseURL: 'https://open-b943d.firebaseio.com',
    storageBucket: 'open-b943d.firebasestorage.app',
    measurementId: 'G-BQ1416VZM1',
  );
}
